// Debugging component to help with testing text.
import React from 'react';

function LoremIpsum({
  }) {
    return (
        <div>
        Lorem ipsum odor amet, consectetuer adipiscing elit. Ultricies rhoncus justo turpis nec natoque sed. Tortor eleifend lobortis eleifend condimentum quam sollicitudin. Ex venenatis vel lobortis tristique hendrerit felis tortor. Conubia himenaeos lobortis finibus dictum sollicitudin consectetur euismod sagittis. Sapien nulla tristique tempus sodales id suspendisse. Mi quis rutrum praesent vel porta fermentum dictumst fermentum mi. Convallis phasellus ligula eu felis efficitur vestibulum cras. Sit bibendum sagittis nunc praesent euismod. 
        Semper aliquam venenatis malesuada tellus platea. Nunc mollis conubia bibendum suspendisse est litora ultricies dignissim. Pharetra sit molestie; velit mauris himenaeos diam quam. Viverra maecenas non cras mauris eget adipiscing. Cras elementum cubilia at; elit pellentesque nunc. Augue enim sagittis nostra at tempor purus senectus quis. Torquent leo fames sem imperdiet parturient pellentesque, vestibulum risus varius?
        Neque cursus venenatis donec pharetra felis leo. Convallis quisque dis curabitur orci in amet turpis condimentum. Rutrum aenean suscipit metus hendrerit leo dis feugiat elit. Porta magnis ut sem, vehicula torquent finibus proin porta. Commodo laoreet cras morbi; placerat habitasse eget posuere metus auctor. Volutpat habitant quis vel imperdiet sapien habitant vulputate eu consequat. Cras quisque per quis id vel placerat per. Sodales enim sit cras hendrerit arcu. Accumsan fames consequat dis et sapien fames per habitasse consequat. Donec amet ac sem aenean aliquet purus condimentum.
        Velit porttitor ac nec netus pellentesque senectus. Accumsan hac rutrum facilisi facilisi faucibus facilisi metus. Facilisi finibus rhoncus phasellus cubilia morbi sollicitudin dictumst. Pharetra ullamcorper convallis massa nullam arcu maecenas magna ultrices nullam. Torquent in sagittis sodales fusce augue. Habitant lobortis odio a magna pretium ullamcorper consequat. Non primis accumsan aliquet sagittis non. Ante risus pellentesque maecenas litora pulvinar ornare mattis orci enim? Taciti eros curae magna amet augue proin magna at.
        Potenti phasellus dictumst curae vivamus ipsum ad arcu nunc. Sapien pulvinar sapien sem netus velit enim. Nulla ridiculus imperdiet sem, non mattis purus facilisi vivamus. Efficitur id curae taciti nascetur malesuada taciti. Ex purus senectus nunc posuere primis elit class. Tristique ullamcorper pretium quis est vehicula etiam. Consequat est euismod ultrices dolor sed.
        Orci donec condimentum ullamcorper a finibus mattis finibus. Felis condimentum dui ornare a cras hendrerit? Pellentesque platea pretium efficitur sociosqu sodales maximus nam dignissim. Duis cursus odio tortor tortor habitasse nibh; urna nisl praesent. Maecenas habitant metus molestie curabitur nullam egestas lectus at. Aliquam ut cras augue eleifend facilisi elementum litora quam massa.
        Penatibus litora venenatis dapibus mi egestas rhoncus. Rutrum vitae pulvinar consequat potenti euismod rhoncus efficitur! Ataciti enim sed nullam inceptos est porttitor. Nunc fames enim dis placerat blandit quisque nibh sed? Tortor erat tellus pulvinar augue finibus proin vitae orci. Facilisis habitasse senectus habitasse maximus sit dictumst consequat purus enim.
        Felis molestie orci eget cras per cursus nisi. Fringilla luctus non condimentum volutpat bibendum interdum. Dapibus netus turpis eros est vivamus mauris. Cursus auctor nisi luctus inceptos purus non nibh? Ultrices vestibulum massa lectus mattis platea, sagittis montes. Purus volutpat netus tincidunt tempus ultricies sodales tincidunt pulvinar! Potenti ante aliquet class elementum pellentesque conubia. Donec fusce eu rhoncus maximus eros. Torquent feugiat venenatis per lectus a feugiat luctus fusce. Accumsan bibendum molestie amet eget nullam.
        Fames massa fermentum potenti elementum quis donec. Feugiat purus placerat ante diam donec metus. Commodo at ultricies habitant ex inceptos quis lectus. Sagittis curabitur laoreet consectetur neque vivamus aliquam donec. Nec velit nibh ante mus quisque cubilia! Eget vulputate amet rhoncus lorem platea elit velit class.
        Neque cras luctus aliquam primis dignissim ante ex. Lacus gravida cubilia lectus velit odio netus, sodales at. Libero dignissim gravida ornare curae accumsan est augue proin lacinia. Fames nullam vitae sociosqu pharetra at odio porta turpis. Facilisis in dolor ad quis interdum mus lacus! Magnis ligula porta pulvinar ipsum tempus senectus auctor turpis. Taciti nibh vestibulum erat viverra maecenas augue mauris accumsan.
        </div>
    );
  }

export { LoremIpsum };